# Old-origin bridge tree (#888, Stage 1).
#
# deming.leedurbin.co.nz stops serving the site and serves the #887 bridge
# instead: a page that carries the reader's saved data to the same path on
# learndeming.org. This builds what the rsync `deploy` job ships to that
# docroot in place of _book/:
#
#   * one copy of deploy/old-origin-bridge.html for every page in _book/,
#     at the same path, with its __NEW_URL__ placeholders filled in. So each
#     copy carries its own canonical link and a <noscript> redirect to the
#     same page on the new origin. That's why it's a copy per page, not one
#     page behind a rewrite: a single static page can't know its own path
#     without JavaScript.
#   * an .htaccess that 301s everything else, path and query preserved, to
#     the new origin: assets, robots.txt, sitemap.xml, unknown paths.
#
# The split relies on how SiteGround serves a request. nginx answers any path
# that exists as a file itself, and passes the rest to Apache, which is the
# only layer that reads .htaccess. So the bridge pages are served as plain
# files, and the 301 only ever sees paths with no file behind them.
#
# Stage 2 (a pure 301 for every path) is this same tree with the pages
# removed, leaving only the .htaccess.

.old_origin_bridge_placeholder <- "__NEW_URL__"

.old_origin_bridge_htaccess <- paste(
  "# Generated by R/functions/old-origin-bridge.R (#888). Do not edit on the server:",
  "# the rsync deploy job overwrites this docroot on every merge.",
  "#",
  "# nginx serves every bridge page directly, because each one is a real file.",
  "# Only paths with no file behind them reach Apache and this rule, and they",
  "# go to the same path on the new origin. The query string is kept. The",
  "# docroot's index.html is a bridge page too, so / is exempt.",
  "DirectoryIndex index.html",
  "RewriteEngine On",
  "RewriteCond %{REQUEST_FILENAME} !-f",
  "RewriteCond %{REQUEST_FILENAME}/index.html !-f",
  "RewriteRule ^ NEW_ORIGIN%{REQUEST_URI} [R=301,L,NE]",
  "",
  sep = "\n"
)

.old_origin_bridge_escape_attr <- function(x) {
  x <- gsub("&", "&amp;", x, fixed = TRUE)
  x <- gsub('"', "&quot;", x, fixed = TRUE)
  x <- gsub("<", "&lt;", x, fixed = TRUE)
  gsub(">", "&gt;", x, fixed = TRUE)
}

#' Fill the bridge template for one page.
#'
#' @param template The template's text.
#' @param new_url The page's URL on the new origin.
#' @return The page's HTML.
render_bridge_page <- function(template, new_url) {
  if (!grepl(.old_origin_bridge_placeholder, template, fixed = TRUE)) {
    stop("bridge template has no ", .old_origin_bridge_placeholder, " placeholder")
  }
  gsub(.old_origin_bridge_placeholder, .old_origin_bridge_escape_attr(new_url), template, fixed = TRUE)
}

#' Build the bridge tree for the old origin.
#'
#' @param site_root The rendered site (`_book`). Every .html file under it
#'   gets a bridge page at the same path.
#' @param out_dir Where to write the tree. It's emptied first.
#' @param template_path The bridge template.
#' @param new_origin The new origin, without a trailing slash.
#' @return The number of bridge pages written.
build_old_origin_bridge <- function(site_root, out_dir, template_path, new_origin) {
  new_origin <- sub("/$", "", new_origin)
  template <- readChar(template_path, file.info(template_path)$size, useBytes = TRUE)
  Encoding(template) <- "UTF-8"

  pages <- list.files(site_root, pattern = "\\.html$", recursive = TRUE)
  if (length(pages) == 0) stop("no .html files under ", site_root)

  unlink(out_dir, recursive = TRUE)
  dir.create(out_dir, recursive = TRUE)

  for (page in pages) {
    dest <- file.path(out_dir, page)
    dir.create(dirname(dest), recursive = TRUE, showWarnings = FALSE)
    html <- render_bridge_page(template, paste0(new_origin, "/", page))
    writeChar(html, dest, eos = NULL, useBytes = TRUE)
  }

  htaccess <- sub("NEW_ORIGIN", new_origin, .old_origin_bridge_htaccess, fixed = TRUE)
  writeLines(htaccess, file.path(out_dir, ".htaccess"), sep = "")
  length(pages)
}
