---
title: "PRELUDE A: UNDERSTANDING A SYSTEM"
execute:
  echo: false
---

What exactly did Dr Deming mean by a "system"? On *The New Economics* page 35 *[50]* he provided this description: ["A system is a network of interdependent components that work together to try to accomplish the aim of the system"]{.deming_quote}. That says a lot in just a single sentence! Note in particular ["work together"]{.deming_quote} and the ["aim"]{.deming_quote}. Let's first consider the "aim" of a system.

## The aim of a system

Simply stated, the *aim* of a system is what the system tries to do. If we are designing a system then it makes obvious sense to first consider carefully what we want its aim to be, and then design it with that preferred aim in mind. With systems that already exist and affect us, it makes sense to learn and understand what their aims are.

Take the case of that beautiful but fearsome animal: a tiger. Besides procreation, let's consider three possibilities for its aim:

1. To regulate the number of animals in a forest;
2. To regulate the number of humans in a settlement;
3. To land up as a carpet in someone's house!

Each aim turns the tiger into a different system: it will behave differently, it will do different things. In the first system the tiger becomes a predator. It stalks smaller animals and has to chase them, outrun them, and finally slay them. In the second system the tiger becomes a man-eater. Now it has to out-think and outsmart a human who is not as strong nor as fast as the tiger itself but is intelligent and has some ability at self-defence. In the third system the tiger becomes the hunted!

Similarly, any individual, organisation, group, or even country has an aim—intentional or otherwise. The aim gives the system a reason for its existence. For example, the Walt Disney company has the aim: "Make every child smile; there is a child in every adult". Bill Gates and Microsoft have the aim: "A computer in every home, on every palm, on every lap, and on every desk". Steve Jobs had the aim: "To offer every product to the customer like a piece of art".

On *The New Economics* page 36 *[51]*, Dr Deming included a suggestion for the aim of a system in which human beings are involved. It was ["for everybody to gain … over the long term"]{.deming_quote}. Of course, this immediately raises a good question: why on Earth would you expect people to ["work together"]{.deming_quote} to achieve any different kind of long-term aim?

## Interconnections

That immediately brings us back to the earlier part of Dr Deming's description of a system: ["a network of interdependent components that work together"]{.deming_quote}. Everything in any system is interconnected. There are no wholly isolated parts in any system. An obvious example is the human body. Every organ is connected to others: no organ exists in isolation. Further, every organ performs a primary function. But it is also likely to perform one or more secondary functions which often remain largely unrecognised by the person whose body it is. For example, the eyes and the ears, along with the sight and the hearing functions that they primarily perform, are also responsible for the body maintaining its balance.

As a consequence of its interconnectedness, it is important to realise that we cannot hope to understand a system by simply breaking it down into its separate components and studying those components in isolation. One cannot learn much about water by separately studying the properties of hydrogen and oxygen. As you know, these are both highly inflammable gases—but when they come together they create something that *quenches* fire! This is an example of a particularly interesting aspect of interconnectedness that is known as *synergy*. I found this definition of synergy in a dictionary: "mutual reinforcement or complementariness". Using simpler and shorter words, such togetherness is often described as being where the result is greater than the sum of the parts. Another example is sugar. Sugar is a hydrocarbon. It may not be advisable to try to taste either hydrogen or carbon, but sugar is pleasant to taste.

A tree is a further interesting example of interconnectedness. If we ask a child to draw a tree, the child (or, for that matter, an adult) would normally draw its trunk, some branches and some leaves. That's because this is what we see. What we do not see are the roots that grow under the ground. In fact, the roots generally grow deeper under the ground than the trees grow above the ground! Another lesser-known fact is that roots, even those belonging to other trees, entwine underground. Scientific study has also proved that not only do the roots entwine but they also *enjoin* underground.

This was documented by a very famous quantum physicist named Dr Fritjof Capra. He wrote extensively about this in his 2002 book: *The Hidden Connections*. There he described his surprise at finding that, irrespective of where trees are physically "rooted" or what kind of trees they are, underground they behave as though they are one! Underground they seem to share everything—that's surely real togetherness! This concept was echoed by Dr Deming long ago in Japan. In 1950 he advised the Japanese Government to collaborate with industry, education and healthcare and to encourage and enable them to all work together as a system to bring Japan out of its crisis. It is thus no surprise that the complete title of his final book is *The New Economics for Industry, Government, Education*. More togetherness.

## The "most important" part of the system

Dr Deming was once asked this question: "What is the most important part of a system?". His answer was not anything like "In the case of a human being it's the heart" or "In the case of an organisation it's the boss". No, his striking answer was simply: ["The part that is not working"]{.deming_quote}.

In one sense, of course, the heart or the boss could be regarded as the most important. But that is in a *negative* sense: the sense of "Which part causes the most harm if it doesn't function as it should?". In contrast, Dr Deming was answering in a *positive* sense. He was thinking in terms of what he called optimisation of a system—"optimisation" means it is working in the *best possible way* to try to achieve its aim. And, in that positive sense, no one component of the system is more important than any other: they are interconnected. If *any* part does not function as it should then the plain fact is that the system is not working in the best possible way. What do we mean by "function as it should"? We mean "help the system as best it can to try to achieve its aim".

Let's consider a further example of interconnectedness. Take the case of a classroom in a college where a lecture is to be conducted. Some obvious components of this system are the classroom, the equipment, the students, the teacher, the topic, the time slot, etc. Let us imagine any one of these components disappearing and examine what would happen to the system. Without students, the lecturer could only talk to the walls. That would not be a lecture: that would be madness! Or without a lecturer, i.e. with only the students staring at the board and nothing going on, it is not a lecture: that is collective madness! Without a classroom, that would just be a gathering, not a lecture. Without equipment, maybe a lecture can be conducted after a fashion, but it is unlikely to be as intended given the fact that nowadays people use technology and "smart" classrooms. Irrespective of considerations about what might be the "most important" part of this system, the point is that, in *every* such case, the system's aim is most certainly *not* being achieved.

This example also provides another illustration of different parts of a system each having an identity both *for* and *because of* each other. A teacher is called a teacher because there are students to *teach*. Students are called students because they are *studying* under a teacher.

## Cause and effect may be far apart

We tend to react to things as they appear before our eyes, in the here and now (rather similarly to drawing that tree, as described on the previous page). But surely it makes sense to delve deeper. For example, if we observe some event then, for better understanding, we need to identify interconnections between that event and other matters, rather than merely jumping to a conclusion based on what appears "obvious" right now. That is, we need to respond to what *caused* the event rather than merely reacting to the event itself.

Finding the cause(s) of an event may, of course, be easier said than done. One reason is that cause and effect are not necessarily closely connected in either time or space. The root causes of an event which occurs right before our eyes may have been somewhere far away and in an altogether different time-frame. Conversely, decisions that we take today may well have consequences in another place and at another time (recall in particular Rules 3 and 4 of the Funnel on Day 3).

As an illustration, consider somebody who has been riding a motorcycle for a couple of years. One day, on his way to work, he goes over a little bump and then finds that his motorcycle has abruptly stopped and refuses to budge. He takes it to a mechanic who tells him that the clutch wire has broken. He might immediately react to this in an annoyed fashion by asking: "One little bump and the \*\*\*\*\* wire breaks?". The truth could be that, because of his habit of "riding the clutch", the clutch wire has been gradually getting more and more frayed throughout all those two years. Finally, when he went over that little bump, it snapped—it was bound to, sooner or later. The fraying had started from the day he bought the bike. So where was the fault? That habit of riding the clutch could well have begun when he was young and received poor instruction when first learning to ride a motorcycle.

Let's consider a longer illustration. A senior manager in a company is taking a walk in the workshop and notices a puddle of oil on the floor underneath a machine. He asks: "What is that puddle of oil doing on the floor?". Immediately a cleaner is called and the oil is removed. The manager is happy. A few hours later, the people notice a fresh puddle of oil has taken its place. The question is repeated: "What is that puddle of oil doing there?". This time they realise that the oil is leaking from the machine. They investigate and find that a bolt has come loose. It is tightened and no further oil leaks out. Great! A few days later, yet another puddle of oil has appeared, and the question is asked for the third time. The bolt is again found to be loose. Now what? Upon further investigation it is found that a washer has broken. The washer is replaced and the bolt is tightened. Excellent: no more oil leakages … until … a week later … another puddle of oil. Now it is found that the washer was of the wrong type. When this is checked in the Parts Store they discover the sad fact that there are 5,000 such washers in stock—all quite useless. Reason? Well, the Purchasing Manager had given instructions for "cutting costs", and so cheap washers had been bought. When the Purchasing Manager is asked why he was cutting costs, he promptly replies that, over a year ago, the Vice-President had told him to. The consequence was that oil kept leaking onto the floor—which turned out to be far more costly than the correct washers would have been—another classic case of cause and effect not closely related in time and space.

A typically perceptive observation from Dr Deming was: ["There are no isolated events, but eventualities"]{.deming_quote}.

## Comparing, competing, ranking, rating

Every person, every part, everything has its importance in a system—else why is it there? Some parts may be able to do absolutely nothing on their own yet have important synergistic relationships with other parts of the system, i.e. help *them* to work better for the system, help the system to achieve its aim.

This brings to light another attribute of a system: since every person or thing has its role to play in the system, how can it be justifiable to compare that person or thing to any other person or thing in the system? It's like, as the saying has it, comparing apples to oranges. We have already argued that thinking positively (and optimisation) it does not make sense to choose a "most important" part of a system, e.g. the heart in a body—nor the brain, nor the kidneys, nor the fingernails, nor the skin, nor the hair on our skin! They're all "most important" because they *all* contribute to optimising the system, and their contribution is different from that which other parts contribute. Also notice that these parts do not in any sense "compete" against each other to try to show their supremacy. Instead, they complement each other; they "work together". This observation becomes particularly pertinent when we consider the human beings in a system.

In the 1970s there were four spin-bowlers in India's cricket team. Each spinner had a certain role to play, a role which was different from the others' roles. Bishen Singh Bedi was a left-arm leg-spinner who always attacked the batsmen, thus forcing them to make errors. Bhagwat Chandrashekhar had a polio-stricken arm and was freakishly unpredictable: thus he was very effective at confusing the batsmen! Erapalli Prasanna was an off-spinner with a lot of variety; he was also deadly accurate, thus tying down the batsmen. Finally Venkataraghavan, who was supposedly the "weakest link" of the four, was actually even more deadly because he beguiled the batsmen to gain false confidence by allowing plenty of runs to be scored off his bowling. There were yet more subtle differences between them, but the point is that they all had their particular roles to play. People made the grave error of comparing these great spinners to each other —who was the "most important"? The easiest way to answer would be to give that credit to whomever had taken the greatest tally of wickets. But how could one justifiably give the credit on that basis when they used to plan the dismissals *together*? It wasn't a competition: it was collaboration, cooperation, working together. None of them was the "most important". Or, if you like, they were *all* most important. Take your pick!

There is something worse than choosing the most important—and sadly it is very common. It is ranking or rating. This is not just choosing the "most important" or the "best", etc, for that's only choosing Number 1. "Ranking" means choosing not only Number 1, but also Number 2 and Number 3 and all the rest! "Rating" is similar but on a cruder scale. If just choosing Number 1 does not make sense, how much more senseless is ranking or rating (unless you're thinking *negatively*)! We have seen that, since a family is a system, it is silly to talk of the "most important" member of the family. In a family consisting of Mother, Father and three children, how much more stupid would it be to rank them as Numbers 1 to 5?

Indeed, ranking and rating are not just senseless—they are harmful. Reflecting the question posed on page 1, why should people ["work together"]{.deming_quote} (for the advantage of the whole system) if sometime soon they are going to be compared in a way which inevitably produces winners and losers? Ranking and rating involves the creation of some kind of scoring operation (such as the tally of wickets for the spin-bowlers). But how can you score "working together"? Any scoring operation needs something to measure or something to count. Especially if some sort of reward and punishment is involved for the winners and losers, the inevitable consequence is people *competing against* each other instead of working together. Worse still, there are always methods for increasing one's score by doing *harm* to the system rather than working to its advantage. A salesman can increase his sales (which is likely to be his "score") by lying to potential customers about how good the product or service is. Someone who works in a call-centre can increase her number of calls per hour (if that is her "score") by not giving the caller sufficient time to explain the problem properly, or by quickly passing the caller onto someone else, or even by cutting off the call as soon as it has been counted, maybe even before she has uttered a single word! If hospitals are negatively scored by the number of deaths during operations, that number is easily reduced by only carrying out less risky operations.

Worse still are examples in education. Children's capabilities are confused with how well they answer the questions in a patterned questionnaire (i.e. a questionnaire whose format and content are largely known beforehand). If schools will be scored and league-tabled according to their students' number of passes in national examinations, the school can train their students to pass examinations rather than developing genuine knowledge and understanding of the subject matter.

When Dr Deming was speaking to Japanese industrialists in the early 1950s, he warned them that they would be in danger of destroying each other if they focused on competing against each other rather than focusing on the customers. ["We must learn to cooperate instead of trying to compete."]{.deming_quote}

## Optimise or maximise?

Thus, in summary, we have emphasised that the different parts of a system need to optimise their combined performances ("work together") rather than maximising their individual performances (as measured by their "scores"). Nature tends to optimise, whereas mankind, especially under bad management, tends to maximise. This, of course, takes us straight back to the salesman and the lady in the call-centre and their good scores for which they were probably rewarded despite causing harm to the system as a whole. Such cases where one part of a system is maximised, but in a way which is to the detriment of the overall system, are what Deming referred to as "*suboptimisation*". If that part of the system is human (an individual, a group, a department, etc), such suboptimisation may be deliberate (again especially under bad management). There are other examples. Proteins are good for the body, but an excess of proteins can actually harm the body by destroying the bones and the nervous system. Oxygen is needed by the body, but an excess of oxygen can actually eat into parts of the body, thus causing decay.

Many years ago, in the early 1970s, if people were diagnosed with high blood pressure, some research showed that this was often related to the blood containing a high level of cholesterol. Very soon, pharmaceutical companies created medicines which they called "cholesterol killers" and released them onto the market. These tablets provided instant results: those blood pressures started dropping dramatically.

However, a few months later, these same people started complaining of low energy levels and low resistance to diseases. The research laboratories went into overdrive and were appalled by what they discovered. There exist two kinds of cholesterol: high-density lipoprotein and low-density lipoprotein. High-density lipoprotein is most surely good cholesterol: this cholesterol is needed to provide the body with energy. On the other hand, low-density lipoprotein is light and floats in the blood: it sticks to the inner walls of the arteries, thus narrowing them. This makes it harder for the heart to pump blood around the body which then results in raised blood pressure. This certainly means that, in order to reduce this stress on the heart, *something* must be done about the low-density lipoprotein. But now the researchers also realised that, since the low-density lipoprotein was present, it must be there for a purpose. They discovered that it was present because it acted as a filter to toxins in the blood. This implied that the low-density lipoprotein needed to be *regulated*, not *destroyed*.

People's contributions to a system also need to be regulated. A favourite example of Dr Deming's was that of an orchestra with 140 players who are all there to work together and support each other. Supporting each other produces harmony. But how loudly each plays needs to be regulated. If any players simply tried to play as loudly as they could then it would result not in harmony but in cacophony. You can probably see some analogies with the lady's number of calls per hour and the salesman's sales.

In the early 1970s, there was a writer-duo in the Indian Film Industry: Salim Khan and Javed Akhtar, often abbreviated to Salim-Javed. Each was a master of his craft, but it was the joint optimisation of their talents that resulted in some phenomenal scripts being written which are remembered and admired to this day. Salim Khan was excellent at creating plots, sequences and characterisations. Javed Akhtar was a poet who wrote lyrics and dialogues for these plots, scenes and characters. Together their results were mind-boggling. Unfortunately they eventually decided to split up, causing sadness to many.

Subsequently they tried to achieve individually what they had done together, but they never succeeded. Javed Akhtar continues to write poetry and dialogue and has won some awards for these but has never really scaled similar heights again. Salim Khan has dabbled in writing a few times but is fairly inactive these days.

## Performing "within limits"

Finally, let me bring together a few of the important illustrations we have described. First, the salesman who lied was in all probability selling more than could reasonably have been accomplished had he spoken the truth rather than lying to potential customers. Second, the lady in the call-centre chalked up more calls per hour than would have been possible had she been giving good service to her callers. In both cases those "good scores" were beyond the limits of what would have been possible if they were doing their jobs properly.

Third, in the case of low-density lipoprotein, its destruction had disastrous results: instead, it needed to be regulated to stay within appropriate limits (not including 0!). Fourth, the amount of proteins and, fifth, the amount of oxygen both need to be regulated rather than maximised: i.e. they also need to be kept within appropriate limits. To put it mildly, too high or (of course) too low amounts will be damaging.

Long ago in your *12 Days to Deming* course you became familiar with the importance of a system or parts of a system or processes performing "within limits"—it was called a state of statistical control. So these thoughts naturally lead us into Prelude B: "Understanding Statistical Thinking".
