---
title: "PRELUDE D: UNDERSTANDING PEOPLE"
execute:
  echo: false
---

As you know, these four Preludes respectively introduce some of the concepts in the four parts of Dr Deming's System of Profound Knowledge which you will study more fully on Days 10 and 11. At the end of Prelude C we again recalled that Deming emphasised these four parts are [all related to each other]{.deming_quote}. It should therefore be of little surprise that, during this final Prelude, we shall see several important links to all of the earlier Preludes.

### "What is the job of a teacher?"

For a start, a particularly important issue which arose in Prelude C is that we are all born with the natural desire to learn. Dr Deming most certainly subscribed to this belief, but also pointed out that [people learn in different ways, and at different speeds]{.deming_quote} (*DemDim* page 278). Some learn by watching. Some learn by doing. Some need a combination of watching and doing. Some need to read. Some need to hear. For some, one word is enough. For others, after ten attempts, the person understands during the eleventh. Some learn faster and some learn slower. Which of all these and other possibilities characterise you? Whichever they are, are they not also things that you were born with?

Further, in Prelude A we saw some of the difficulties and indeed harm caused by ranking and rating. And now we surely see yet more. As there are so many different inherent ways of learning, is it then even *possible* for you or anyone else to sensibly rank people Number 1, Number 2, Number 3, … ? Are you not effectively ranking what those people were born with and perhaps, to some extent, how they were brought up? That doesn't sound very fair—they are not responsible for either. In any case, what determines "better" or "worse" as far as you are concerned except for what happen to be your own personal preferences? For example, in the quick learner "better" than the slow learner? Why? The slow learner may well finish up understanding more deeply. So again, what determines your choice between "better" and "worse"?

But are we not subjected to this kind of illogicality throughout our lives? When you brought your report-card home from school for the first time, wasn't the first question asked: "Who came top of the class?". Even worse, maybe you were then told: "Go and study with her/him next time". Why? What is the theory behind such thinking? Is it that if I studied with that person then I would be top of the class too?

Well, if that is the case, this can be harmful in at least two ways. First: trying to be someone that you're not. Second: crushing your *natural* learning process. I leave it to you to figure out which is worse. And imagine the despondency all around if you still do not finish top.

So what should be done instead? As seniors—parents, teachers, managers—our real job is to *discover a person's natural learning process*. That person could be your child, your student, your colleague. Is there some standard method of doing this? Well, some psychologists claim that such methods do exist. Maybe. But I suggest that simply spending more time with the children or the others, getting to know them and thus making it possible to discover their natural learning processes, would be a good place to start. How? Watch what they do and what makes that child get excited, what makes that student's eyes light up, what makes that person at your place of work go the extra mile to get the job done. Those are the signs we need to look out for. Those are the things that keep people awake at night. Those are the feelings we need to hone. Those are the sparks we need to ignite and keep burning.

Dr Deming was once asked: "What is the job of a teacher?". He replied that a teacher has three obligations to his students: (1) to make them fall in love with the subject, (2) to provide thorough subject-matter knowledge, and (3) to discover their inherent learning processes so that the subject makes more sense to them. I think we need to read and re-read that reply and apply it to our lives. Through that reply, Deming not only clearly defines the importance of discovering a person's natural learning process but also then the need to sharpen the point of that discovery to where that person may start *enjoying* his work and learning. In so doing, Dr Deming has also clearly defined our jobs as teachers, parents and managers. Be prepared!

### Does pay "motivate"?

When we discover and understand people's learning processes, whether they be our children, our students or our colleagues at work, and then we put them on the right jobs or give them something appropriate to study, it often becomes hard to stop them working! We will then have given them what Deming had no hesitation in describing as "Joy in learning" and "Joy in work".

During this course, you have doubtless become used to the fact that Dr Deming sometimes came out with statements which could be described as "startling"! There will be at least two such statements during this final Prelude. There is, of course, a risk in producing a statement that people may find startling. They may react by jumping to the conclusion that the statement cannot be true and therefore that the person making it doesn't know what he's talking about! Hopefully, by now, you know enough about Dr Deming *not* to jump to such a conclusion, even if you do not understand right now why he said something. He would make such "startling" statements for a definite purpose: to challenge you, to make you *think*, and think hard—much harder than if he always came out with something "tame", something with which you would instead readily agree. You may recall from Prelude B that he learned the importance of teaching in this manner from none other than Dr Shewhart.

During one of his seminars at General Motors in Michigan, Deming came out with such a "startling" statement about pay. It was:

> ["Pay is not a motivator!"]{.deming_quote}

In *The Deming of America* video, he repeated those exact words. This certainly startled Priscilla Petty, his interviewer! Deming then recalled that occasion at General Motors, and continued:

> ["Sure you have to have enough to live on, and to live right. Beyond that, pay is not a motivator. Remember Norb Keller's statement which I think is famous. On the 7th of November 1987, Mr Norb Keller of General Motors at a meeting stated that, if General Motors were to double the pay of everybody commencing the 1st of December, nothing would change. Performance would be exactly what it is now."]{.deming_quote}

(This statement is revisited on *The New Economics* page 74 [109].) So if your salary were doubled, starting tomorrow, will your work improve? You would doubtless be pleased, but would your work *improve*? By comparison, Deming believed that if your learning or your opportunities to learn were increased even by just a little then yes, your work would improve, maybe by a considerable amount—even without any extra money!

He often recalled "someone in history" (never named as far as I know) who apparently stated that (1) if we want to work then we go to an office, whereas (2) if we want to study then we go to school, and (3) if we want to play then we go to a playground. He would then ask whether there was any law to say that we couldn't also have fun and play at our place of work.

Now, don't start jumping to wrong conclusions here. What he meant was that, if my learning process were known and understood, and I was therefore put onto the appropriate kind of job, I would *start enjoying* what I do and begin to constructively "play around" with my work, thinking differently, looking for improvements and creating ideas for innovation. Rather than merely doing the same old thing day in and day out, I would be focused all the time on helping to make things *better*. I would also need to *study* my product or process in order to enable this to happen. Wouldn't I now *look forward* to going to work every day in such circumstances? It would certainly be far more fulfilling and exciting!

One of the most important reasons that the Japanese became so successful was that they did understand this. They focused on putting the right people in the right jobs and, as a result, saw unparalleled results. They were fostering and building upon people's *intrinsic* motivation. Intrinsic motivation lights a fire *inside* people so that they continue to perform what they are doing without really feeling the heat!

But what do we see in the name of "motivation" these days? We get *extrinsic* motivation. Managers and others think that people get motivated by dangling a carrot in front of them or by comparing one with another and creating artificial competition. Well, in contrast, this seems to me to be akin to lighting a fire *underneath* people rather than *inside* them! The consequence is that, the moment you remove the fire, they will stop doing what you want them to do. Why not, if you have removed the only reason they were doing it? Can you expect anything new or innovative in those circumstances? In such circumstances, people will not take risks any more as they will be too busy doing the right things wrong. In contrast, in the better approach, the whole concept of learning encourages people to be interested and to experiment and to take risks, and often this leads to huge successes. Did any useful innovation ever come about without some ["risk of being wrong"]{.deming_quote}? (Recall the beginning of Prelude C.)

The most damaging effect of extrinsic motivation is that it so often kills off that priceless intrinsic motivation with which we were born. We train children from a young age that, in order to get a "reward", they must behave well, or do their homework, or finish their chores. So their reason to do such good things is no longer that those things are good: the reason is to be given the reward. They will no longer behave well, do their homework, or finish their chores for the pleasure of doing good things or for the pleasure given to others for their so doing.

Rather than dangling that carrot in front of a child ("If you do that then I'll reward you like this"), were we instead to give them the privilege of enjoying their learning, their reward would be in the learning itself. Does that sound altruistic and far-fetched? It is not. It is scientific, systemic, emotional and logical, all at the same time. Besides, of course, it has been done before. Why stop now? It can be done again.

### Competition

During Day 8 you have already seen another "startling" statement, this time on *DemDim* page 219 when reading about competition in Chapter 15. It was:

> ["Competition has ruined us."]{.deming_quote}

At least, I imagine it startled you at the time: it has that effect on most people. Hardly surprising. Many regard competition as the salvation, the panacea, for all economic woes. If Governments consider there to be too little competition in an industrial sector, they introduce laws to increase competition. In schools or in a company's Sales Department, there are methods for ranking the pupils or the salespeople, with prizes going to "Number 1", the "winner".

During Day 8 there was much emphasis on the advantages of cooperation over competition. The Major Activity there was an effective demonstration of the gains that cooperation can produce—so much so that Dr Deming later included a version of that demonstration in *The New Economics*. In the "Comparing, competing, ranking, rating" section of Prelude A we have already introduced some thoughts about competition and its effects. We shall now build on those thoughts and include a number of illustrations. What is particularly relevant to the current Prelude is the effect on people when they are *forced* to compete.

You will probably be familiar with Charles Darwin's famous expression: "Survival of the Fittest". People have often interpreted this in the sense of "Red in Tooth and Claw". That is a misunderstanding. Instead, Darwin said something quite different in *The Origin of Species*: that the species which will survive is the one that can adapt itself fastest to its ever-changing surroundings. But such a misunderstanding has resulted in our believing that we can only survive by eliminating the others around us. Agreed, in a game or in a beauty contest, we knew before we started that there could be only one winner—that's the rule. However, later on you will see Deming's concise explanation of the type of situation which he wanted to create, for example in Business and in Education. It was: ["Everyone will win; no losers"]{.deming_quote}. In case you find that concept too much to accept at first sight, we have already seen (e.g. on Prelude A page 1) Deming instead using the word "gain" in a similar context. Business and Education can have more than one winner—and they need to. It depends on how you define "winning". In fact, even in a game or a sport there can be more than one "winner".

That was the original concept of the Olympic Games. The Greeks created the Olympics for a very different purpose from "one winner". They had travelled far and wide and learned that there were many, many different countries with many, many different kinds of people. Wouldn't it be wonderful if people from all over the world could come together and learn about each other's cultures, habits, rituals, knowledge and understanding—besides, of course, making new friends? *Everybody* would win. That is why and how they conceptualised the Olympic Games. They wanted a joyous event with indoor and outdoor games where people would learn and gain from each other. But, somewhere down the line, it turned into just a competition. It is rare that we see any sharing and learning between the athletes today. Rather than sharing and learning, they simply regard each other as rivals because now there can be only one "winner".

This has led to a relative scarcity of "winners". People no longer engage in sport for the purpose of remaining fit and healthy throughout their lives: they just play to win. This has led to their using all kinds of means—fair and unfair—in order to win. Nowadays one can name numerous athletes who have consumed unnatural substances so that they could become physically more capable of winning than their counterparts. Today, where are these athletes? What is their physical and mental state? Are they "fit and healthy"?

One genuinely fit and healthy athlete does come readily to my mind. That is the great Dara Singh, who always believed in being fit and healthy the natural way. The bouts that he won were not won because he trained to *win*: rather, he trained to be *the fittest*. The winning was a natural *by-product* and *consequence* of his being so fit. Sadly, I regard him as being something of an exception.

### Competing against or competing with?

It is useful to consider competition in two forms: competing *with* and competing *against*. One might term them *friendly* and *unfriendly* competition respectively. In effect, we have just seen both cases. The Olympic Games began in the spirit of competing *with*: competing with each other *for everybody's benefit*. The Olympics later degenerated into merely competing *against*.

One of the best examples of beneficial competing *with*—including competing with oneself! Vijay Amritraj is one of the best tennis players that India has ever produced. Every player in his era, including Borg and Connors, was wary of him. I would like to tell you about a Davis Cup match that he played toward the end of his long career. It was the last of the five matches to be played in a contest which was currently tied at 2–2: so Vijay just *had* to win it. His opponent was a young seeded player who was half his age and twice as fast. Vijay lost the first two sets. In the third set he was 1–4 down and then on his serve he was 15–40 down. From this precarious position, he went on to win the match 3 sets to 2.

In the post-match conference, he was asked what was going on in his mind at the instant just described. His answer was simple: "I was too focused on trying to beat the other player. I suddenly realised that, if I had to compete, it had to be with *myself*. I needed to be improving my own game. So I began focusing on myself. Suddenly I found that I was winning and, before I knew it, the match was in my pocket."

He was making the point just mentioned: he had been competing *against* instead of competing *with* and thus was losing out. When he reversed his thinking, everything—including the match—turned in his favour. Deming taught the same thing to the Japanese. He taught them that, instead of focusing on the other company (competing *against*), organisations should be focusing on the customer and how close they can get to the customer (competing *with*): that was the only way they would be able to put out better products and service.

I remember a nasty joke one of my students blurted out when I mentioned this in class. He said: "If you keep looking at your competitor and what he is doing when you are in business then your product will end up looking like the competitor's backside!" I think that summed it up most aptly!

### Is it "natural" to compete *against*?

Understanding the distinction between "competing with" and "competing against" can make all the difference between success and failure. But, if we look around us, we find that we always seem to be involved in competition *against* someone in some form or other. Children compete against each other for the attention of their parents at home and their teachers at school; grown-ups compete against each other to attract the attention of their bosses; friends compete against each other to grab attention in a group. We see and experience this competition and manifestations of this competition all around us. Many claim that we are born with these traits. Deming argued otherwise. His claim was that, instead of being born with such traits, we *acquired* them because of the way we were treated while and since we were children. We have been taught from a young age that, in order to get ahead, someone else has to lose.

Let me tell you about a fancy-dress festival organised as part of a school gathering at a famous school in Pune. All the children came dressed in the most ridiculous of outfits and were having a great time pulling each others' legs and making jokes with each other. They were really enjoying themselves—until the Chief Guest decided to turn this into a fancy-dress *competition*. That's when everything went haywire. Children started fighting each other, some of them started spoiling another child's dress so that they themselves could win. Then the *parents* started fighting each other! The organisers had a tough time controlling the crowd after that. It all got really out of hand when the results were announced. Many of the parents complained bitterly of being cheated out of a prize. There were also cases where the parents were yelling at their children because they did not say their "dialogues" right.

What do you think—is the trait of competing against each other and its consequences *born* with us or was it *acquired* by us? I am sure that very many of us have faced similar situations, only we did not look at them in this way. The children's joy of participation was replaced by the despair of having lost the prize. Do children *really* need to be jolted by what we earlier learned to call "extrinsic" motivators? Would it not be better to instead build upon their natural *intrinsic* motivation?

I believe I see parallels between this sequence of events at the fancy-dress festival and the above history of the Olympic Games.

Finally in this section, I cannot help but recall the times when, in school and college, there used to be prizes and "stars" for the work that we did. Those who were awarded the highest marks were decorated with these prizes and stars. This was done to supposedly motivate the other children. But did it *really* do that? I think not. I remember spending sleepless nights wishing the others in the class would do badly so that I would get the first prize and be decorated with a star. Was this "motivation"? And what about the others? What do you think they were wishing for every other student? Going to school became a nightmare.

Today I see people leaving for their places of work without a smile on any face. They go there and spend the day trying to outdo the others in order to catch management's attention. One doesn't rise up the ranking without being noticed. Deming said that the place of work should be like a playground. But what has the workplace become? No longer a playground: instead, a battlefield. In Deming's eyes, the "unfriendly" type of competition, competing *against*, destroys individuals.

So, as we shall see on the next page, in *The New Economics* Dr Deming said that our need is to ["restore the individual, and do so in the complexities of interaction with the rest of the world"]{.deming_quote}. He saw that failure to do so would be a major obstacle to a nation's growth. As an important contribution, he taught the Japanese that a manager must understand that, in an organisation, people work *in* the system whereas the job of managers is to work *on* the system, in order to improve it. How? Encouraging and enabling people to take pride and joy in their work is fundamental. For this there needs to be continual learning. This is the combination that results in continual improvement. He had already advocated the removal of the dreaded "performance appraisal" system which actually does not really "motivate" a person at all. How many do you know that look forward to their annual appraisal? So how *could* it be "motivational"?

### Are we no better than rats?

The notion that people always need a "reward" for doing good things has become so deep-seated that Dr Deming occasionally fell into the same trap himself! He referred to this mistake as "overjustification". Toward the end of his days he often told his audiences at four-day seminars of the occasion when he had arrived on a flight from America to England. He was tired, frail, stooped, clearly very old. An air-hostess at Heathrow was kind to him and carried his luggage for him all the way to the exit. When they reached the exit, Deming put his hand into his pocket and fished out 50 dollars to pay her for this extra service that she had provided. His intention was, of course, to make her happy with this gift. Instead, she politely declined and went away. He realised later that he had hurt her. She had done it for the joy of helping someone in need, and he had turned that joy into sadness by thinking about her the way that he did. He writes with clearly deep regret about this and other similar occasions on *The New Economics* pages 75–77 [110–113].

This sad way of thinking and acting is encouraged by the work of a very famous psychologist who, to quote the author mentioned below, "conducted most of his experiments on rodents and wrote most of his books about people". How strange! To think that we are being compared with rats in our behaviour patterns. Think about it! I will not name that psychologist here, but be sure he did *not* contribute to Deming's "Knowledge of Psychology" (the fourth part of the System of Profound Knowledge). However, if you would like to know who he was and read more about him, I refer you to the opening pages of Alfie Kohn's fascinating book: *Punished by Rewards* from which the above description is taken.

One of the experiments the said psychologist conducted was the famous "Rat and Cheese" test. He would put a piece of cheese on a platform in a rat cage, following which the rat would come out of his little block in the cage and walk down a path leading to the cheese. He would take it and go back into his block. This led the psychologist to believe, and make others believe, that nobody would do anything without being coerced, or the equivalent thereof.

Alfie Kohn wrote the whole story of the "Rat and Cheese" from the viewpoint of the rat! He went on to describe how the rat concluded: "Whenever I come dancing down the path to fetch the cheese, the man puts out yet more cheese for me". So—who was really controlling whom? Might it not have been that things were happening the other way round?!
