---
title: "INTRODUCTION"
execute:
  echo: false
---
## DAY 9: A SYSTEM ... OF PROFOUND KNOWLEDGE

Today's material is in two very distinct halves. As implied by the form of the above title, this morning's focus is on the concept of a "system". You are, of course, already quite familiar with this concept. But I would like to further develop your understanding of it, or indeed your *appreciation* of it---Dr Deming often used the phrase ["appreciation for a system"]{.deming_quote}. When you first saw that on [Day 1 page 39](../day-01/11-deming-story.qmd#sec-page39) it might have struck you as a rather odd choice of word---at least, that's what I thought when I first heard it. If that's still the case with you then I believe it will seem rather less odd to you by the end of this morning.

Today's complete title without the central break, i.e. ["A System of Profound Knowledge"]{.deming_quote}, relates not only to this afternoon but also to the Second Project over the next two days. This afternoon firstly introduces you to what Dr Deming meant by that phrase and then moves on to preparing you for the Second Project in which you will take a very close look at some of what he wrote on it.

This morning's reading-matter is relatively short; but there is still plenty for you to do! In contrast, there is only reading for you this afternoon, although it is of some extensively varied styles. You will therefore have plenty of time for it, and it will be well worth that time. (I'm not being boastful: most of it wasn't written by me!)

Chapter 3 of *The New Economics* is "Introduction to a System". As already pointed out, that would not really be an "Introduction" as far as you are concerned. The treatment here, though, is very different from that in his Chapter 3. The latter is substantial and wide-ranging. As an example, his portrayal of the exercise in yesterday's Major Activity is contained within that chapter. By comparison, my treatment this morning is relatively brief. It does, however, add some useful background material that strengthens the foundations of both the theory and the practice of the system concept---some of which material again stretches back to (guess whom!) Dr Walter Shewhart.

I would describe what I have included in this morning's material as just sketching a background, rather like an artist's very broad brush-strokes at the earliest stages of creating a painting, with all the detail to be gradually filled in later. One reason for keeping this quite short is to allow you plenty of time for today's Major Activity which is to develop an "Organisation Viewed as a System" flow diagram for your organisation, guided by Deming's famous diagram that you saw as early as [Day 1 page 25](../day-01/08-attraction.qmd#sec-page25). You may recall that the diagram appeared there as the very first of his ["Summary of Teachings to Top Management and to Engineers in Japan"]{.deming_quote}. This is really important. For after all, as we shall see, Dr Deming did describe that flow diagram as ["the spark that turned Japan around"]{.deming_quote}. So, quite some spark! For your convenience it is reproduced on the next page.

You may fear that constructing a flow diagram for your organisation could be something of a tall order. You may think you do not know enough about your organisation to be able to complete such a diagram. If so, that might in itself tell you something about the organisation! However, in fact, the task may not be as daunting as you could be imagining. For Deming's system diagram is also "very broad brush": it involves only relatively *major* components of the system rather than details that you may well not know about. It is not a "flow chart" in the usual sense of that term since flow charts usually get into lots of "nitty-gritty" detail---that is not what is needed in Deming's diagram whose nature is instead very "macro". I shall re-emphasise this when the time comes. In any case, at this stage, getting a completely "right answer" is not what is important. It is the *learning* and *understanding* that are important. If not there currently, right answers will come later.
