---
title: "... OF PROFOUND KNOWLEDGE"
execute:
  echo: false
---
## ... OF PROFOUND KNOWLEDGE

### Our "12 Days" --- what's left?

The structure of this course is largely chronological, beginning with Shewhart's understanding of variation and then concentrating on Dr Deming's teaching during the 1980s. Now we reach the 1990s, his final four years. I began today by pointing out that Chapter 3 of *The New Economics* is "Introduction to a System", obviously directly related to this morning's work. The fourth chapter in *The New Economics* is titled "A System of Profound Knowledge". Not only is that chapter directly related to this afternoon's material, it is also directly related to the next two days' work which will mostly involve studying Deming's exact words.

On Day 1 page 39 I described Deming's System of Profound Knowledge as "his attempt, sometimes with the wisdom of hindsight, to summarise the core, the guts, the essence of his whole life's work". But that doesn't mean we should forget about his earlier teaching! I know some people who became so excited about the System of Profound Knowledge that they almost seemed to regard the 14 Points etc as "kid's stuff"! Oh no. We shall be revisiting those two famous lists of guidance from the 1980s: the 14 Points (for adoption) and the Deadly Diseases (for cure), which we studied with respect to the Joiner Triangle in the First Project on Days 4 and 5. But now, of course, we shall instead study them directly with respect to the System of Profound Knowledge itself. Recall from Day 6 page 6 that, having described the System of Profound Knowledge as ["the outside view"]{.deming_quote} (*The New Economics* page 64[93]), Dr Deming then simply stated:

> ["The 14 Points for management ... in industry, education, and government follow naturally as application of this outside knowledge, for transformation from the present style of Western management to one of optimisation."]{.deming_quote}

Apart from a similar statement in the Preface and a brief reference to Point 1 on page 36 [51], this is in fact his only mention of the 14 Points *in the whole book*! So Dr Deming was clearly now leaving it to us to figure out how and why the 14 Points follow *naturally* from the System of Profound Knowledge---not forget about them! The purpose of his teaching, after all, was not to simply give us answers but, more importantly, to get us to *think* and to *understand*, which will then better enable us to deal with the "nitty-gritty" of his earlier work. And that is what we shall endeavour to do here in the Second Project on Days 10 and 11.

Deming's Chapter 4 has an obvious five-part structure: firstly an introduction to the System of Profound Knowledge, followed by its four parts:

**A.** Appreciation for a system;

**B.** Some knowledge of theory of variation (sometimes he called it "statistical theory");

**C.** Theory of knowledge;

**D.** Knowledge of psychology.

The five half-days from here through to the end of Day 11 follow the same five-part structure, though I have adjusted the balance quite a lot.

Finally, on Day 12, we shall do a number of things to finally "bring it all together"---at least as far as we can within the context of a course such as this. There was one fallacy in my analogy near the beginning of the course about Dr Deming's theory of management being like a large jigsaw. The difference about this jigsaw is that, the more you work at it so that the more pieces you fit together, the more pieces seem to keep materialising---ones that you hadn't seen before! So there will be yet further contributions to your lifelong learning! And remember what (good) theory is for: the more (good) theory you have and the better you understand it, the more help you will have for guiding you and your organisation toward better practice---which was the purpose of Dr Deming's teaching, and my own purpose in developing this course.

### Development of "Profound Knowledge"

It will be helpful at this point for you to **read through a short section in *DemDim*: page 259 to two-thirds down page 261.** This will give you some general background and a brief history of the development of Dr Deming's work on "Profound Knowledge" during those final years of his life.

You may notice that the titles of the four parts of the System of Profound Knowledge as presented on *DemDim* page 261 are slightly different from those that you have just seen here. That is not unusual---Dr Deming himself did not always stick exactly to the same words. The same is true of other authors. For example, you already saw other slight variations in the titles long ago in Peter Scholtes's diagrammatic representation on Day 1 page 39. Take a quick look at it again if you've forgotten it.

### Sources of learning

Such is the nature of the System of Profound Knowledge that it is valuable to have more than one source of reference in order to obtain a better-rounded appreciation of its content. The material that follows here through to the end of Day 11 is based on Deming's May 1990 version referred to on *DemDim* page 260.

I have always liked the May 1990 version which is reproduced in its entirety within the material between today's page 24 and the end of Day 11 (the relevant material on Days 10 and 11 also being in the Workbook), unchanged apart from occasional rewording and reordering. Part C on the Theory of Knowledge is the shortest of the four parts and so, during the morning of Day 11, I shall include extra material on two important topics of direct relevance to that part: operational definitions and the Shewhart Cycle.

One attraction to me of this 1990 version is its *compactness*. Issue after issue that Dr Deming raises is stated with extraordinary economy of words---something at which he excelled. But such compactness rarely makes it easy to read. Making it easy wasn't his purpose! His intention was instead to provide focus for thought and study in a much more effective way than ordinary text can do. Indeed, Parts B and C and some of Part D are written as lists, with most items on the lists containing no more than two sentences!

Coincidentally, *DemDim* was first published at about the same time as the May 1990 version of the System of Profound Knowledge. However, as you will have just read on *DemDim* page 260, my Chapter 18 was "revised" two years later---in fact, it was almost completely rewritten! And so your second source of learning is that chapter in *DemDim*: it should become your constant companion throughout the next two Days.

The third, and of course ultimately the most important, source must naturally be Dr Deming's final book: *The New Economics for Industry, Government, Education*. I have already pointed out that our material here for Days 9–11 is guided by the pattern of his Chapters 3 and 4. But note that several of the topics to be covered both here and in *DemDim* Chapter 18 are discussed elsewhere in *The New Economics* rather than solely within those two chapters.

With these three sources you therefore have (1) the opportunity to study the System of Profound Knowledge as it was in the relatively early days, May 1990, of its development; then (2) as it was halfway through its time of development in *DemDim*'s rewritten Chapter 18; and then (3) through Dr Deming's final writings in *The New Economics*. Although *The New Economics* is considerably shorter than *Out of the Crisis*, you will not be able to get very deeply into it within the context of this course without a considerably greater commitment of time---so I'm not expecting you to do so. However, looking ahead, I would suggest that *The New Economics* should be top of your reading-list immediately after you have completed this course in order to consolidate your learning. But don't be tempted to try to make enormous use of it during the Second Project (especially in view of the final sentence of the previous paragraph!) or, again, you're unlikely to be able to work through the project in anything like my recommended length of time.

### Guidance for the Second Project (Days 10 and 11)

So---how to approach the System of Profound Knowledge? Not an easy question when faced with the start of some lifelong learning! But I hope you will find the following guidance to be useful advice on how to proceed fruitfully with the Second Project, your initial attempt to learn something substantial about it. There's a lot of detail here, but there's a one-page summary of my suggested procedure on page 29.

I shall ask you to thoroughly familiarise yourself with the following guidance *before* starting Day 10. I'm introducing these thoughts to you now to enable you to carefully consider in advance the issues involved.

It has probably occurred to you already that, with our big build-up to the System of Profound Knowledge---along with its very name and the description of it as "Deming's legacy", etc---two days may not be enough time to learn all about it. If so, you'd be right!

So let's be clear about the purpose of this two-day project. In one sense it is ambitious, but not ridiculously so. In another sense it's quite limited: the purpose is definitely not "to learn all about it"! The role of this project with respect to the whole System of Profound Knowledge mirrors the role of the Overture on Day 1 with respect to this course as a whole. So let me recall a few words from the opening page of Day 1. Relating an Overture to a musical production I said, "It sets the scene by including several of the main themes from the show, and gives some tasters of the moods and style of what is to follow." With a few changes of words, we could now say something like: "The Second Project sets the scene by including several of the main themes from the System of Profound Knowledge and gives you some tasters of its mood and style". The Overture provided you with a good "feel" about what was in the show---but it was no replacement for the show itself. This project is similarly no replacement for comprehensive and deep learning on "Deming's legacy"---that will take much more than two days (dare I mention "lifelong learning" yet again?). What you learn in this course is just a start---a good start, I trust, but just a start nonetheless.

Presumably, long ago when you read our Overture, you found some things that you could immediately understand. On the other hand, some of what I said there may have seemed almost incomprehensible at the time---hopefully, less so by now! I imagine the majority of the content lay somewhere between those two extremes. The same will be true here concerning the System of Profound Knowledge. There is a lot to cover in two days, so be warned that you won't have a lot of time to figure things out. If you were to take the time to try to get on top of everything which will be introduced here then two days would soon expand into two weeks or two months or probably much more!

In a way, the limitation to two days is actually an advantage. You will know from the start that it will be impractical for you to spend ages thinking about individual items. Why is that an advantage? Because, at this early stage, dwelling lengthily on particular matters would result in your study of the four parts of the System of Profound Knowledge being far too spread out---and the serious consequence of that is the danger that you would largely miss the way that the four parts are *interdependent and complement each other*. When you reach Dr Deming's introduction a little later this afternoon you will find that his opening sentence is: ["The System of Profound Knowledge appears here in four parts, *all related to each other*"]{.deming_quote} (my italics). What's vital is for you to get a good sense of that *interleaving nature even if plenty of the detail* of what's in the four parts may remain rather hazy for the time being. So the aim of this project is for you to acquire a "big-picture" view. Filling in the details will come in time---but then at least you will understand what you are filling them into! These two days will be just your initial scratch of the surface. As time goes on you will dig through that surface in order to expose the hidden depths that lie beneath.

I'll divide the work you'll carry out on each part of the System of Profound Knowledge into four steps that I will describe over the next two and a half pages and are summarised on page 29 [also on WB 151]. These four steps will be broadly followed in each case, but will be slightly modified when desirable.

### Step 1: Browsing session

There are various possibilities about how to tackle each part of the System of Profound Knowledge respectively over the four half-days. I'll describe some of them to you, to help you decide what is most appealing to you. There is no "best" choice. As Deming observed in the "Knowledge of Psychology" section (see e.g. *DemDim* page 278), ["People learn in different ways"]{.deming_quote}, and that's why it needs to be largely your personal choice. So please be patient as you consider the various options: your choice is important. You could, for example, make an immediate start on considering in turn and in detail each of the individual issues that Dr Deming raises, following his text as reproduced during Days 10 and 11. Or, before that, you might prefer to get an advance taste of what is to come by reading through all of the text for that half-day up to the beginning of the relevant Activity. Also, if you're in "advance browsing" mood, you might like to read through the relevant section of *DemDim* Chapter 18---not particularly slowly or carefully initially but just to help set the scene. I shall ask you at Step 3 to study those pages from *DemDim* (even if you have already browsed through them earlier) after working through all the individual issues; you will get more out of that section in Chapter 18 at that stage. For your reference, both here within the course and in the future, I shall include the relevant page numbers from both *DemDim* and *The New Economics* within each part during the Second Project.

There is one piece of advance reading that I shall definitely recommend for you near the start of each half-day. Later this afternoon I'll ask you to read some relatively gentle introductory material on the System of Profound Knowledge---certainly gentler than Dr Deming's own writing! I will tell you about this on page 23. So, to help set the scene, I definitely suggest you should re-read the relevant part of that material before starting on the main business of each half-day. To accommodate this and other advance reading suggested above, my timing guidance will usually include a half-hour for browsing before you get down to the main work. Depending on how much you decide to do, you may not need the whole half-hour. In that case, make an early start on the "real work" so that, for a little while at least, you'll be ahead of the clock!

### Step 2: Dr Deming's May 1990 version

Now comes the most substantial section of each half-day in which you will work through the relevant part of the 1990 version of the System of Profound Knowledge, item by item. Following what I said a little earlier, you know that Dr Deming's descriptions of the various items in this version are extremely succinct. You have had a taste of that style several times already during the course. You are also aware that, during the project, you'll have fairly limited time to spend on each issue.

Again there's a variety of possibilities for how to proceed. As in Step 1, I'll run through some of them here so that, as before, you'll be able to get a sense of what appeals to you and what doesn't. Also, if you can think of yet further possibilities for what would help your learning---fine, try them out.

One obvious possibility of how to start---and this will certainly be quick and easy---is for you to describe your immediate reaction(s) upon reading an item. There is a space after each item in which to write your comments, questions, thoughts. Remember that, in many cases, there won't be much to read---maybe just one short sentence! Examples of such immediate reactions might be: "Really important" or "I'm already familiar with this" or "My organisation is doing the direct opposite to that". Other immediate reactions might be in the form of questions such as "Why is he saying this?" or "What does he mean by that?" or "What does this imply?". In fact, immediate reactions in the form of questions would be very useful since you could then spend the available time by trying to answer them! Some initial reactions which are not originally in the form of questions could also soon lead to questions, like "Why is my organisation doing the direct opposite to this?" or "What would be the benefits if my organisation stopped doing the direct opposite to this?".

If your initial reaction was "I'm already familiar with this", fine, but don't just leave it at that! Particularly if it's a topic on which you are at this stage quite knowledgeable, write a brief explanation of it---maybe one or two or three sentences. One benefit is that, later on, if you've forgotten some of the detail, your explanation could save some time. More importantly, writing an explanation will help with further thinking: for example, a very useful thought would be "Yes, and not only that ..."! If nothing else, do as Deming would have done---think and ask---and observe how the item relates to other topics throughout the System of Profound Knowledge.

More suggestions on how to proceed will be given in the individual Sections. But as the above examples might have suggested to you, do *not* worry about being unsure or even quite confused about some of the items! I must stress this because if you consider that to be a hindrance and that it is only going to get worse then you might lose heart. The important thing is to keep going and deal with what you can deal with. Look at the brighter side: whatever you can deal with should inspire you---it will almost certainly make you think, and make you *want* to think more, and that will indeed come in time. Meanwhile, recall what I said on Day 2 page 16: ["Don't only think that you don't know---think about what you do know!"]{.deming_quote}

Other suggestions for what you might include are any illustrations from your own experience relevant to what Dr Deming is talking about, and also any important connections you see with earlier material in this course. Remember that here I am deliberately offering a range of choices for how you spend the available time---I'm not expecting you to do *everything* that I'm mentioning! To put it mildly, your time will be limited---one *could* often spend *hours* on a single item rather than just a few minutes. I'll try to help you by using the little clock icons. The purpose of jotting down your comments, questions, etc in this way is to serve as "memory joggers" for future reference, and as pointers to issues that you think need particular emphasis or particular extra thought. Some of these memory joggers will be useful to you during the Second Project when you tackle the relationships with the 14 Points and the Deadly Diseases, also with the Major Activity on Day 12, and also---as, of course, I hope you will---when you continue to study and learn from the System of Profound Knowledge long after you have completed this course.

Now, all this may well sound rather ambitious! But don't worry. I know there will be times when e.g. you won't be able to get very far because you don't yet understand well enough what Deming is driving at with a particular item. That is *not* unusual! In such a case, after spending a little time thinking about it but not making much progress, simply move on to the next item. Remember the jigsaw analogy yet again. When you first look at some pieces that you have not yet fitted into the jigsaw, they can appear quite meaningless to you---you just can't see what they are or where they could possibly fit in. But you will be able to see where some *other* pieces can fit in. And eventually, as the picture grows, those pieces will help you to also see where and how your previous "mystery" pieces belong. Therefore when you find items on which, after two or three minutes thought, you feel you can't write down anything very useful at the moment: don't try---their time will come. (But you might then need to interpret the clock icons more flexibly during Step 2.)

### Step 3: *DemDim* version

Having finished your detailed work on the individual issues in each half-day, then read through the appropriate part of *DemDim* Chapter 18 irrespective of whether or not you browsed through it earlier. Now, and again while doing so, you'll probably find it useful to update some of your earlier comments. The *DemDim* chapter may provide help with some of the questions you had noted down, and certainly will put more flesh on the bones in places. There will also be space for you to note down any additional relevant comments from Chapter 18, since some further issues will have been raised there (for, remember, it was written two years after Dr Deming's material which is reproduced here).

### Step 4: Activity (connections with the Points/Diseases)

Here I will first ask you to comment on what you see as the importance of addressing the 14 Points and curing the Deadly Diseases *in light of your learning from that part of the System of Profound Knowledge*. You should not spend long over this. You have already become familiar with the 14 Points and Deadly Diseases on Days 4 and 5, and many of the links with the Joiner Triangle that you spotted there will be relevant here also.

To support that remark it is worth pointing out that, as you'll probably have realised, there are some pretty obvious connections between the three vertices of the Joiner Triangle and the four parts of the System of Profound Knowledge. For example, the first part of the System of Profound Knowledge is "Appreciation for a System". Surely our thoughts about the horizontal rather than the vertical "organisation chart" are wholly related to "All One Team". Similarly, "Optimisation of a System" and the aim or purpose of the system must surely have something to do with an "Obsession With Quality". Again, the "Scientific Approach" has clear connections with both the second and third parts of the System of Profound Knowledge: "Knowledge of Variation" and "Theory of Knowledge". Then the fourth part of the System of Profound Knowledge is "Psychology"---people---and there can be no doubt that all three emphases from the Joiner Triangle are very much to do with people: how they need to be treated and how they can be enabled to realise their full potential. So, on Days 4 and 5 you saw plenty of connections between the 14 Points and curing the Deadly Diseases with messages from the Joiner Triangle, you will also immediately see plenty of connections with the System of Profound Knowledge. Use them!

The final phase of the work will be for you to indicate on a simple 0–5 scale what, at that stage, you understand and appreciate as the strength of the links between the relevant part of the System of Profound Knowledge and adopting the Points and curing the Diseases. These data will be used early on Day 12 to provide some personalised guidance for your further study and learning.
