---
title: "INTRODUCTION"
execute:
  echo: false
---
## DAY 7: TARGETS, APPRAISALS, PERFORMANCE INDICATORS, QUOTAS, SPECIFICATIONS, PAY FOR PERFORMANCE, FINANCIAL INCENTIVES, LEAGUE TABLES AND OTHER OBSTACLES

For those who attended one of Dr Deming's four-day seminars but arrived with little prior knowledge of what he would be saying (as was the case with most of those delegates in London in July 1985), his verbal onslaughts against performance appraisals and numerical targets generally hit them as being among the most controversial aspects of his teaching. Also, to those many whose "way of life" regarding quality was all about meeting specifications, requirements, standards and so on, his insistence on their inadequacy would be greeted with some shock and disbelief. But, as pointed out long ago ([Day 1 page 27](../day-01/09-different.qmd#sec-page27)), "Deming is Different". *(However, he did always come up with good reasons for being different!)*

In fact, these topics and others in today's title are all strongly interrelated. As an obvious example, the appraisal of your performance often includes how you have measured up against various targets (objectives, requirements, goals) that were set for you a year previously—officially with your agreement, I imagine (as if you had any option).

Some 35 or so years later, our situation has become both paradoxical and self-contradictory. On the one hand, numerous people now have some considerable awareness of the shortcomings of employing such methods and techniques in management and, indeed, in government—particularly, of course, the majority who are at the receiving end of these approaches. Many now speak passionately on the dangers of e.g. the "target culture" and performance-related pay: we have just seen examples toward the end of Day 6. And it seems to me that the large majority of these are not bad, lazy people who are primarily interested in sitting away their time and getting away with the absolute minimum possible effort and involvement in their work. From what I have seen and heard, far more often they are those who are—or, sadly, in some cases, were (past tense)—wholly committed to their work, wanting nothing better than to be able to do a great job for their organisations and their customers. Instead, they are increasingly frustrated by the obstacles and disincentives created by such "management techniques" as just mentioned, having found that they only serve to prevent them from doing that great job as opposed to providing anything supportive.

Why do these techniques have such harmful effects? If you worked successfully at the First Project on Days 4 and 5, you are already well able to produce answers to that question. But cynics, because of their negative view of "theory", might try to argue that those answers are "merely theoretical". Very well, if they instead need practical examples, let them read and argue against the proliferation of short true stories already commenced toward the end of Day 6 and the many more which continue here, starting on page 9.

Yet managements and governments still actively persist in using these things, despite both the theory and the facts.

You will recall that we have more than touched upon several of these topics previously; e.g.

1. performance appraisal directly through the third Deadly Disease and indirectly through Point 12 (pride of workmanship);

2. numerical targets directly through Point 11 and indirectly through the fifth Deadly Disease (dependence on only visible figures); and

3. the limited nature of judging quality or performance in terms of merely satisfying requirements or reaching standards, specifications or targets through our discussions on such matters as continual improvement and delighting customers as opposed to merely satisfying them.

But these are such crucial topics that we should take a further look at them. And there are yet more.

"The supposition that it is only necessary to meet specifications" is the 13th in an even longer "list" from Dr Deming than the 14 Points: one of "a whole parade of obstacles", as he expresses it on *Out of the Crisis* page 107[126]. I have treated these "obstacles" rather briefly in *DemDim* (pages 52–55), and so I need to say more about them here. On that same page in *Out of the Crisis* Deming pointed out that "most of them are easier to cure than the Deadly Diseases"—so, at early stages of trying to figure out useful changes that could be made in your organisation, perhaps some of these might be worth your consideration. The Obstacles are generally more focused than the very wide-ranging 14 Points and the Deadly Diseases, which is perhaps why they are not quite so "famous" as the Points and Diseases. However, because of that tighter focus, they may be found easier to understand and to deal with. You will work on these "Obstacles to the Transformation" as today's Major Activity.

However, before that, we shall spend time on the particular Obstacle just cited. I've already hinted at the reason. Probably more than any of the other Obstacles, the one concerning the meeting of specifications challenges what is still very common practice, making it worth closer attention. Also, although one might imagine that this topic of "meeting specs" is primarily appropriate for manufacturing, some simple changes of words soon make clear that it has far wider relevance. Deming's implication that conformance to specifications is an inadequate judgment of quality is important way beyond just manufacturing contexts.

But the argument can be taken even further, and this is what we shall show—or, indeed, you will show—in a sequence of Activities and Pauses for Thought immediately preceding today's Major Activity. (These Activities and Pauses for Thought are mostly "red", i.e. there is continued discussion immediately following within the main text rather than in the Appendix.) The context there is not manufacturing, but again the argument is relevant both to manufacturing and much more widely.

Much of our work in the course so far has contained a mixture of things to start doing and things to stop doing—and why. Our study of the 14 Points and Deadly Diseases in the First Project was, of course, a substantial example. But today we concentrate almost entirely on things to stop doing. In contrast, the remainder of the course mostly turns attention onto what to do instead.

Today's study is, in essence, structured in four parts. The work just described on conformance to specifications is the third of those four parts, and the Major Activity on the Obstacles is the final part. Returning to this first part, here we have rather a mixture. After this introduction, we first expand upon our previous considerations of targets, i.e. the "numerical goals" of Point 11, with some clarifications of what kinds of goals and targets are the real menace, and why. There is then some discussion on the related matter of Performance Indicators. After that, I briefly look ahead and suggest some "Do"s and "Don't"s for when the time comes to start actively thinking of putting theory into practice.

Finally, I'll say a little about the second of the four parts, which continues the series of short true stories that began toward the end of Day 6. There is rather more involved with these true stories than just browsing through them! As with the true stories on Day 6, the stories here provide material that you can and should use in a number of today's Activities. You will meet Activities 7–a and 7–b (pages 4 and 5) before reaching today's stories, and so you should use yesterday's stories, along with any of your own, when initially working at those two Activities. But, later on, you should then return to these Activities and add to what you will already have written, now using some of today's new material. While reading through today's stories you should also be recording some thoughts in advance for Activity 7–d. Take a quick look at that now: it's on page 18. It's up to you as to whether you choose to read through the whole batch of stories first and then go back to work on the Activities, or do both simultaneously. Do whichever comes more naturally to you. But, in either case, and very importantly, also note down your own experiences that any of these true stories bring to your mind.

I gave you a relatively easy time yesterday. But today definitely needs a full day's work!
