#!/usr/bin/env Rscript
# Assemble docs/deviations-from-source.md from the per-entry source files in
# docs/deviations/. Run this from the repository root after adding, editing,
# or removing an entry, then commit the resulting docs/deviations-from-source.md
# alongside your per-entry change.
#
# Source of truth:
#   docs/deviations/_preamble.md
#   docs/deviations/YYYY-MM-DD-slug.md   (one file per entry)
#
# Output:
#   docs/deviations-from-source.md       (build artifact, regenerated each run)
#
# Sort order: filenames sorted descending. The YYYY-MM-DD prefix gives
# newest-first chronological order across days; within the same date, entries
# fall in alphabetical order by slug.

if (!dir.exists("docs/deviations")) {
  stop("Run this from the repo root — docs/deviations/ not found.")
}
preamble_path <- "docs/deviations/_preamble.md"
if (!file.exists(preamble_path)) {
  stop("Missing docs/deviations/_preamble.md")
}

entry_files <- list.files(
  "docs/deviations",
  pattern = "^[0-9]{4}-[0-9]{2}-[0-9]{2}-.+\\.md$",
  full.names = TRUE
)
entry_files <- sort(entry_files, decreasing = TRUE)

banner <- c(
  "<!--",
  "  Generated by scripts/build-deviations-log.R.",
  "  Do not edit this file directly — edit per-entry source files in",
  "  docs/deviations/ and re-run the build.",
  "-->",
  ""
)

preamble <- readLines(preamble_path)

entry_blocks <- lapply(seq_along(entry_files), function(i) {
  body <- readLines(entry_files[[i]])
  if (i == 1L) c("---", "", body) else c("", "---", "", body)
})

output <- c(banner, preamble, "", unlist(entry_blocks), "")
writeLines(output, "docs/deviations-from-source.md")

cat(sprintf(
  "Wrote docs/deviations-from-source.md (%d entries).\n",
  length(entry_files)
))
