---
title: '"OUT-OF-HOURS" NOTE'
execute:
  echo: false
---

## Congratulations---you're halfway through this important project!

### "Out-of-hours" note

As you will remember, the preparation I recommended before you began the Second Project comprised three sections. Two of those sections (on the four-step procedure and on your previous work in the First Project) should now be as familiar to you that you'll need no further preparation on them. That leaves the second of the three sections, which previously only concerned Parts A and B. So, in your remaining preparation for the second half of this project, you will similarly need to spend some time on the relevant material in Balaji's Preludes and in *DemDim* Chapter 18, i.e. those which relate to Parts C and D.

In both cases there are no more than three pages for you in *DemDim* Chapter 18: pages 274–276 and pages 277–279 respectively. In Balaji's Preludes also pages 15–19 and 20–25. As previously, I suggest you always have Peter Scholtes's diagram from [Day 9 page 22](../day-09/06-introductions-to-the-system.qmd#sec-page22) in front of you to keep you focused on a small number of main features and the nature of these two Parts.

So firstly, carefully read through Balaji's Prelude C and then *DemDim* pages 274–276, making notes on where you see the links between them. Prelude C very helpfully and straightforwardly concentrates on a particular aspect of the Theory of Knowledge which otherwise you might possibly have found to be the most challenging. A consequence is, of course, that it does not include anything on some other important issues, but hopefully you will find them adequately covered in *DemDim* Chapter 18 and in the course material tomorrow. Nevertheless, the coverage in both *DemDim* Chapter 18 and in Dr Deming's May 1990 version is shorter than with the other three Parts, and so I have included some additional reading tomorrow morning: *DemDim* Chapter 7 on Operational Definitions and Chapter 9 on the Deming Cycle. Therefore, if you have the time, you might also like to take a quick advance look at those two chapters. Prelude C does not refer to either of these topics, although in effect the concept of the Deming Cycle is hinted at. If, during tomorrow, you find yourself becoming interested in the important topic of operational definitions then, for your *future* reference, I'll point you toward the excellent Chapter 9 in *Out of the Crisis*.

But don't forget to prepare for Part D as well! So, following the previous pattern, first remind yourself of what's in Prelude D. Then read through *DemDim* pages 277–279, making notes of the links that you see with what Balaji has included in his Prelude. Then you'll be ready to roll!

<div class="separator">
  <div class="separator_white">
  <div class="separator_blue"></div>
  </div>
</div>
